// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jwt_tokens.sql

package repos

import (
	"context"
)

const createJwtToken = `-- name: CreateJwtToken :one
INSERT INTO jwt_tokens (jti, role, user_id, is_blacklist, expired_at)
VALUES (?, ?, ?, 0, ?)
RETURNING id, jti, role, user_id, is_blacklist, blacklist_at, expired_at, created_at, updated_at
`

type CreateJwtTokenParams struct {
	Jti       string `json:"jti"`
	Role      string `json:"role"`
	UserID    int64  `json:"user_id"`
	ExpiredAt *int64 `json:"expired_at"`
}

func (q *Queries) CreateJwtToken(ctx context.Context, arg CreateJwtTokenParams) (JwtToken, error) {
	row := q.db.QueryRowContext(ctx, createJwtToken,
		arg.Jti,
		arg.Role,
		arg.UserID,
		arg.ExpiredAt,
	)
	var i JwtToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.Role,
		&i.UserID,
		&i.IsBlacklist,
		&i.BlacklistAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJwtTokenByJti = `-- name: GetJwtTokenByJti :one
SELECT id, jti, role, user_id, is_blacklist, blacklist_at, expired_at, created_at, updated_at FROM jwt_tokens WHERE jti = ? LIMIT 1
`

func (q *Queries) GetJwtTokenByJti(ctx context.Context, jti string) (JwtToken, error) {
	row := q.db.QueryRowContext(ctx, getJwtTokenByJti, jti)
	var i JwtToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.Role,
		&i.UserID,
		&i.IsBlacklist,
		&i.BlacklistAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJwtTokenByJtiAndBlacklist = `-- name: GetJwtTokenByJtiAndBlacklist :one
SELECT id, jti, role, user_id, is_blacklist, blacklist_at, expired_at, created_at, updated_at FROM jwt_tokens WHERE jti = ? AND is_blacklist = ? LIMIT 1
`

type GetJwtTokenByJtiAndBlacklistParams struct {
	Jti         string `json:"jti"`
	IsBlacklist *int64 `json:"is_blacklist"`
}

func (q *Queries) GetJwtTokenByJtiAndBlacklist(ctx context.Context, arg GetJwtTokenByJtiAndBlacklistParams) (JwtToken, error) {
	row := q.db.QueryRowContext(ctx, getJwtTokenByJtiAndBlacklist, arg.Jti, arg.IsBlacklist)
	var i JwtToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.Role,
		&i.UserID,
		&i.IsBlacklist,
		&i.BlacklistAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJwtTokenByJti = `-- name: UpdateJwtTokenByJti :exec
UPDATE jwt_tokens
SET is_blacklist = ?, blacklist_at = ?
WHERE jti = ?
`

type UpdateJwtTokenByJtiParams struct {
	IsBlacklist *int64 `json:"is_blacklist"`
	BlacklistAt *int64 `json:"blacklist_at"`
	Jti         string `json:"jti"`
}

func (q *Queries) UpdateJwtTokenByJti(ctx context.Context, arg UpdateJwtTokenByJtiParams) error {
	_, err := q.db.ExecContext(ctx, updateJwtTokenByJti, arg.IsBlacklist, arg.BlacklistAt, arg.Jti)
	return err
}

const updateJwtTokensByUserID = `-- name: UpdateJwtTokensByUserID :exec
UPDATE jwt_tokens
SET is_blacklist = ?, blacklist_at = ?
WHERE user_id = ?
`

type UpdateJwtTokensByUserIDParams struct {
	IsBlacklist *int64 `json:"is_blacklist"`
	BlacklistAt *int64 `json:"blacklist_at"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) UpdateJwtTokensByUserID(ctx context.Context, arg UpdateJwtTokensByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateJwtTokensByUserID, arg.IsBlacklist, arg.BlacklistAt, arg.UserID)
	return err
}
