// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package repos

import (
	"context"
)

const deleteOldContainerMetrics = `-- name: DeleteOldContainerMetrics :exec
DELETE FROM container_metrics
WHERE timestamp < CAST(strftime('%s', 'now', ?) AS INTEGER)
`

func (q *Queries) DeleteOldContainerMetrics(ctx context.Context, strftime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldContainerMetrics, strftime)
	return err
}

const deleteOldServerMetrics = `-- name: DeleteOldServerMetrics :exec
DELETE FROM server_metrics
WHERE timestamp < CAST(strftime('%s', 'now', ?) AS INTEGER)
`

func (q *Queries) DeleteOldServerMetrics(ctx context.Context, strftime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldServerMetrics, strftime)
	return err
}

const getLastNContainerMetrics = `-- name: GetLastNContainerMetrics :many
WITH recent_container_metrics AS (
	SELECT id, timestamp, container_id, container_name, metrics_json
	FROM container_metrics
	WHERE container_name = ? OR container_name LIKE ?
	ORDER BY timestamp DESC
	LIMIT ?
)
SELECT id, timestamp, container_id, container_name, metrics_json FROM recent_container_metrics ORDER BY timestamp ASC
`

type GetLastNContainerMetricsParams struct {
	ContainerName   string `json:"container_name"`
	ContainerName_2 string `json:"container_name_2"`
	Limit           int64  `json:"limit"`
}

type GetLastNContainerMetricsRow struct {
	ID            int64  `json:"id"`
	Timestamp     int64  `json:"timestamp"`
	ContainerID   string `json:"container_id"`
	ContainerName string `json:"container_name"`
	MetricsJson   string `json:"metrics_json"`
}

func (q *Queries) GetLastNContainerMetrics(ctx context.Context, arg GetLastNContainerMetricsParams) ([]GetLastNContainerMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLastNContainerMetrics, arg.ContainerName, arg.ContainerName_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLastNContainerMetricsRow{}
	for rows.Next() {
		var i GetLastNContainerMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ContainerID,
			&i.ContainerName,
			&i.MetricsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastNServerMetrics = `-- name: GetLastNServerMetrics :many
WITH recent_metrics AS (
	SELECT timestamp, cpu, cpu_model, cpu_cores, cpu_physical_cores, cpu_speed, os, distro, kernel, arch, mem_used, mem_used_gb, mem_total, uptime, disk_used, total_disk, network_in, network_out
	FROM server_metrics
	ORDER BY timestamp DESC
	LIMIT ?
)
SELECT timestamp, cpu, cpu_model, cpu_cores, cpu_physical_cores, cpu_speed, os, distro, kernel, arch, mem_used, mem_used_gb, mem_total, uptime, disk_used, total_disk, network_in, network_out FROM recent_metrics ORDER BY timestamp ASC
`

type GetLastNServerMetricsRow struct {
	Timestamp        int64   `json:"timestamp"`
	Cpu              float64 `json:"cpu"`
	CpuModel         string  `json:"cpu_model"`
	CpuCores         int64   `json:"cpu_cores"`
	CpuPhysicalCores int64   `json:"cpu_physical_cores"`
	CpuSpeed         float64 `json:"cpu_speed"`
	Os               string  `json:"os"`
	Distro           string  `json:"distro"`
	Kernel           string  `json:"kernel"`
	Arch             string  `json:"arch"`
	MemUsed          float64 `json:"mem_used"`
	MemUsedGb        float64 `json:"mem_used_gb"`
	MemTotal         float64 `json:"mem_total"`
	Uptime           int64   `json:"uptime"`
	DiskUsed         float64 `json:"disk_used"`
	TotalDisk        float64 `json:"total_disk"`
	NetworkIn        float64 `json:"network_in"`
	NetworkOut       float64 `json:"network_out"`
}

func (q *Queries) GetLastNServerMetrics(ctx context.Context, limit int64) ([]GetLastNServerMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLastNServerMetrics, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLastNServerMetricsRow{}
	for rows.Next() {
		var i GetLastNServerMetricsRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Cpu,
			&i.CpuModel,
			&i.CpuCores,
			&i.CpuPhysicalCores,
			&i.CpuSpeed,
			&i.Os,
			&i.Distro,
			&i.Kernel,
			&i.Arch,
			&i.MemUsed,
			&i.MemUsedGb,
			&i.MemTotal,
			&i.Uptime,
			&i.DiskUsed,
			&i.TotalDisk,
			&i.NetworkIn,
			&i.NetworkOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveContainerMetric = `-- name: SaveContainerMetric :exec
INSERT INTO container_metrics (
	timestamp, container_id, container_name, metrics_json
) VALUES (
	?, ?, ?, ?
)
`

type SaveContainerMetricParams struct {
	Timestamp     int64  `json:"timestamp"`
	ContainerID   string `json:"container_id"`
	ContainerName string `json:"container_name"`
	MetricsJson   string `json:"metrics_json"`
}

func (q *Queries) SaveContainerMetric(ctx context.Context, arg SaveContainerMetricParams) error {
	_, err := q.db.ExecContext(ctx, saveContainerMetric,
		arg.Timestamp,
		arg.ContainerID,
		arg.ContainerName,
		arg.MetricsJson,
	)
	return err
}

const saveServerMetric = `-- name: SaveServerMetric :exec
INSERT INTO server_metrics (
	timestamp, cpu, cpu_model, cpu_cores,
	cpu_physical_cores, cpu_speed, os,
	distro, kernel, arch, mem_used, mem_used_gb,
	mem_total, uptime, disk_used, total_disk,
	network_in, network_out
)
VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
	?, ?
)
`

type SaveServerMetricParams struct {
	Timestamp        int64   `json:"timestamp"`
	Cpu              float64 `json:"cpu"`
	CpuModel         string  `json:"cpu_model"`
	CpuCores         int64   `json:"cpu_cores"`
	CpuPhysicalCores int64   `json:"cpu_physical_cores"`
	CpuSpeed         float64 `json:"cpu_speed"`
	Os               string  `json:"os"`
	Distro           string  `json:"distro"`
	Kernel           string  `json:"kernel"`
	Arch             string  `json:"arch"`
	MemUsed          float64 `json:"mem_used"`
	MemUsedGb        float64 `json:"mem_used_gb"`
	MemTotal         float64 `json:"mem_total"`
	Uptime           int64   `json:"uptime"`
	DiskUsed         float64 `json:"disk_used"`
	TotalDisk        float64 `json:"total_disk"`
	NetworkIn        float64 `json:"network_in"`
	NetworkOut       float64 `json:"network_out"`
}

func (q *Queries) SaveServerMetric(ctx context.Context, arg SaveServerMetricParams) error {
	_, err := q.db.ExecContext(ctx, saveServerMetric,
		arg.Timestamp,
		arg.Cpu,
		arg.CpuModel,
		arg.CpuCores,
		arg.CpuPhysicalCores,
		arg.CpuSpeed,
		arg.Os,
		arg.Distro,
		arg.Kernel,
		arg.Arch,
		arg.MemUsed,
		arg.MemUsedGb,
		arg.MemTotal,
		arg.Uptime,
		arg.DiskUsed,
		arg.TotalDisk,
		arg.NetworkIn,
		arg.NetworkOut,
	)
	return err
}
