// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repos

type ActivityLog struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Activity  string `json:"activity"`
	Source    string `json:"source"`
	ClientIp  string `json:"client_ip"`
	CreatedAt int64  `json:"created_at"`
}

type Group struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type GroupPolicy struct {
	ID        string `json:"id"`
	GroupID   string `json:"group_id"`
	PolicyID  string `json:"policy_id"`
	CreatedAt int64  `json:"created_at"`
}

type JwtToken struct {
	ID          string `json:"id"`
	Jti         string `json:"jti"`
	Role        string `json:"role"`
	UserID      string `json:"user_id"`
	IsBlacklist *int64 `json:"is_blacklist"`
	BlacklistAt *int64 `json:"blacklist_at"`
	ExpiredAt   *int64 `json:"expired_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Policy struct {
	ID        string `json:"id"`
	Action    string `json:"action"`
	CreatedAt int64  `json:"created_at"`
}

type TwoFactor struct {
	ID          string `json:"id"`
	Secret      string `json:"secret"`
	BackupCodes string `json:"backup_codes"`
	UserID      string `json:"user_id"`
}

type User struct {
	ID              string  `json:"id"`
	Email           *string `json:"email"`
	LastName        *string `json:"last_name"`
	FirstName       *string `json:"first_name"`
	Avatar          string  `json:"avatar"`
	Role            *string `json:"role"`
	AboutMe         *string `json:"about_me"`
	Password        string  `json:"password"`
	IsEmailVerify   *int64  `json:"is_email_verify"`
	EmailVerifyAt   *int64  `json:"email_verify_at"`
	TwoFactorEnable *int64  `json:"two_factor_enable"`
	IsRegistered    int64   `json:"is_registered"`
	AddedBy         *string `json:"added_by"`
	GroupID         string  `json:"group_id"`
	CreatedAt       int64   `json:"created_at"`
	UpdatedAt       int64   `json:"updated_at"`
}
