// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package repos

import (
	"context"
)

const createGithubProvider = `-- name: CreateGithubProvider :one
INSERT INTO github_providers (
	github_app_name, github_app_id, github_client_id, github_client_secret,
	github_installation_id, github_private_key, github_webhook_secret, git_provider_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, github_app_name, github_app_id, github_client_id, github_client_secret, github_installation_id, github_private_key, github_webhook_secret, git_provider_id, created_at, updated_at
`

type CreateGithubProviderParams struct {
	GithubAppName        *string `json:"github_app_name"`
	GithubAppID          *int64  `json:"github_app_id"`
	GithubClientID       *string `json:"github_client_id"`
	GithubClientSecret   *string `json:"github_client_secret"`
	GithubInstallationID *string `json:"github_installation_id"`
	GithubPrivateKey     *string `json:"github_private_key"`
	GithubWebhookSecret  *string `json:"github_webhook_secret"`
	GitProviderID        int64   `json:"git_provider_id"`
}

func (q *Queries) CreateGithubProvider(ctx context.Context, arg CreateGithubProviderParams) (GithubProvider, error) {
	row := q.db.QueryRowContext(ctx, createGithubProvider,
		arg.GithubAppName,
		arg.GithubAppID,
		arg.GithubClientID,
		arg.GithubClientSecret,
		arg.GithubInstallationID,
		arg.GithubPrivateKey,
		arg.GithubWebhookSecret,
		arg.GitProviderID,
	)
	var i GithubProvider
	err := row.Scan(
		&i.ID,
		&i.GithubAppName,
		&i.GithubAppID,
		&i.GithubClientID,
		&i.GithubClientSecret,
		&i.GithubInstallationID,
		&i.GithubPrivateKey,
		&i.GithubWebhookSecret,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBitbucketProviderByGitProviderID = `-- name: GetBitbucketProviderByGitProviderID :one
SELECT id, bitbucket_username, bitbucket_email, app_password, api_token, bitbucket_workspace_name, git_provider_id, created_at, updated_at FROM bitbucket_providers WHERE git_provider_id = ? LIMIT 1
`

func (q *Queries) GetBitbucketProviderByGitProviderID(ctx context.Context, gitProviderID int64) (BitbucketProvider, error) {
	row := q.db.QueryRowContext(ctx, getBitbucketProviderByGitProviderID, gitProviderID)
	var i BitbucketProvider
	err := row.Scan(
		&i.ID,
		&i.BitbucketUsername,
		&i.BitbucketEmail,
		&i.AppPassword,
		&i.ApiToken,
		&i.BitbucketWorkspaceName,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBitbucketProviderByID = `-- name: GetBitbucketProviderByID :one
SELECT id, bitbucket_username, bitbucket_email, app_password, api_token, bitbucket_workspace_name, git_provider_id, created_at, updated_at FROM bitbucket_providers WHERE id = ? LIMIT 1
`

func (q *Queries) GetBitbucketProviderByID(ctx context.Context, id int64) (BitbucketProvider, error) {
	row := q.db.QueryRowContext(ctx, getBitbucketProviderByID, id)
	var i BitbucketProvider
	err := row.Scan(
		&i.ID,
		&i.BitbucketUsername,
		&i.BitbucketEmail,
		&i.AppPassword,
		&i.ApiToken,
		&i.BitbucketWorkspaceName,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiteaProviderByGitProviderID = `-- name: GetGiteaProviderByGitProviderID :one
SELECT id, gitea_url, gitea_internal_url, redirect_uri, client_id, client_secret, access_token, refresh_token, expires_at, scopes, last_authenticated_at, git_provider_id, created_at, updated_at FROM gitea_providers WHERE git_provider_id = ? LIMIT 1
`

func (q *Queries) GetGiteaProviderByGitProviderID(ctx context.Context, gitProviderID int64) (GiteaProvider, error) {
	row := q.db.QueryRowContext(ctx, getGiteaProviderByGitProviderID, gitProviderID)
	var i GiteaProvider
	err := row.Scan(
		&i.ID,
		&i.GiteaUrl,
		&i.GiteaInternalUrl,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastAuthenticatedAt,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiteaProviderByID = `-- name: GetGiteaProviderByID :one
SELECT id, gitea_url, gitea_internal_url, redirect_uri, client_id, client_secret, access_token, refresh_token, expires_at, scopes, last_authenticated_at, git_provider_id, created_at, updated_at FROM gitea_providers WHERE id = ? LIMIT 1
`

func (q *Queries) GetGiteaProviderByID(ctx context.Context, id int64) (GiteaProvider, error) {
	row := q.db.QueryRowContext(ctx, getGiteaProviderByID, id)
	var i GiteaProvider
	err := row.Scan(
		&i.ID,
		&i.GiteaUrl,
		&i.GiteaInternalUrl,
		&i.RedirectUri,
		&i.ClientID,
		&i.ClientSecret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastAuthenticatedAt,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubProviderByGitProviderID = `-- name: GetGithubProviderByGitProviderID :one
SELECT id, github_app_name, github_app_id, github_client_id, github_client_secret, github_installation_id, github_private_key, github_webhook_secret, git_provider_id, created_at, updated_at FROM github_providers WHERE git_provider_id = ? LIMIT 1
`

func (q *Queries) GetGithubProviderByGitProviderID(ctx context.Context, gitProviderID int64) (GithubProvider, error) {
	row := q.db.QueryRowContext(ctx, getGithubProviderByGitProviderID, gitProviderID)
	var i GithubProvider
	err := row.Scan(
		&i.ID,
		&i.GithubAppName,
		&i.GithubAppID,
		&i.GithubClientID,
		&i.GithubClientSecret,
		&i.GithubInstallationID,
		&i.GithubPrivateKey,
		&i.GithubWebhookSecret,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubProviderByID = `-- name: GetGithubProviderByID :one
SELECT id, github_app_name, github_app_id, github_client_id, github_client_secret, github_installation_id, github_private_key, github_webhook_secret, git_provider_id, created_at, updated_at FROM github_providers WHERE id = ? LIMIT 1
`

func (q *Queries) GetGithubProviderByID(ctx context.Context, id int64) (GithubProvider, error) {
	row := q.db.QueryRowContext(ctx, getGithubProviderByID, id)
	var i GithubProvider
	err := row.Scan(
		&i.ID,
		&i.GithubAppName,
		&i.GithubAppID,
		&i.GithubClientID,
		&i.GithubClientSecret,
		&i.GithubInstallationID,
		&i.GithubPrivateKey,
		&i.GithubWebhookSecret,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabProviderByGitProviderID = `-- name: GetGitlabProviderByGitProviderID :one
SELECT id, gitlab_url, gitlab_internal_url, application_id, redirect_uri, secret, access_token, refresh_token, group_name, expires_at, git_provider_id, created_at, updated_at FROM gitlab_providers WHERE git_provider_id = ? LIMIT 1
`

func (q *Queries) GetGitlabProviderByGitProviderID(ctx context.Context, gitProviderID int64) (GitlabProvider, error) {
	row := q.db.QueryRowContext(ctx, getGitlabProviderByGitProviderID, gitProviderID)
	var i GitlabProvider
	err := row.Scan(
		&i.ID,
		&i.GitlabUrl,
		&i.GitlabInternalUrl,
		&i.ApplicationID,
		&i.RedirectUri,
		&i.Secret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.GroupName,
		&i.ExpiresAt,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabProviderByID = `-- name: GetGitlabProviderByID :one
SELECT id, gitlab_url, gitlab_internal_url, application_id, redirect_uri, secret, access_token, refresh_token, group_name, expires_at, git_provider_id, created_at, updated_at FROM gitlab_providers WHERE id = ? LIMIT 1
`

func (q *Queries) GetGitlabProviderByID(ctx context.Context, id int64) (GitlabProvider, error) {
	row := q.db.QueryRowContext(ctx, getGitlabProviderByID, id)
	var i GitlabProvider
	err := row.Scan(
		&i.ID,
		&i.GitlabUrl,
		&i.GitlabInternalUrl,
		&i.ApplicationID,
		&i.RedirectUri,
		&i.Secret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.GroupName,
		&i.ExpiresAt,
		&i.GitProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
