// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server.sql

package repos

import (
	"context"
)

const getServerSSHCredentials = `-- name: GetServerSSHCredentials :one
SELECT
	sr.ip_address,
	sr.username,
	sr.port,
	sh.public_key,
	sh.private_key
FROM servers sr
LEFT JOIN ssh_keys sh ON sr.ssh_key_id = sh.id
WHERE sr.id = ?
`

type GetServerSSHCredentialsRow struct {
	IpAddress  string  `json:"ip_address"`
	Username   string  `json:"username"`
	Port       int64   `json:"port"`
	PublicKey  *string `json:"public_key"`
	PrivateKey *string `json:"private_key"`
}

func (q *Queries) GetServerSSHCredentials(ctx context.Context, id int64) (GetServerSSHCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getServerSSHCredentials, id)
	var i GetServerSSHCredentialsRow
	err := row.Scan(
		&i.IpAddress,
		&i.Username,
		&i.Port,
		&i.PublicKey,
		&i.PrivateKey,
	)
	return i, err
}
