// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_keys.sql

package repos

import (
	"context"
)

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (
	name, description, private_key, public_key, last_used_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, private_key, public_key, last_used_at, created_at, updated_at
`

type CreateSSHKeyParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	PrivateKey  string  `json:"private_key"`
	PublicKey   string  `json:"public_key"`
	LastUsedAt  *int64  `json:"last_used_at"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, createSSHKey,
		arg.Name,
		arg.Description,
		arg.PrivateKey,
		arg.PublicKey,
		arg.LastUsedAt,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrivateKey,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :one
DELETE FROM ssh_keys WHERE id = ? RETURNING id, name, description, private_key, public_key, last_used_at, created_at, updated_at
`

func (q *Queries) DeleteSSHKey(ctx context.Context, id int64) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, deleteSSHKey, id)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrivateKey,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSHKeyByID = `-- name: GetSSHKeyByID :one
SELECT id, name, description, private_key, public_key, last_used_at, created_at, updated_at FROM ssh_keys WHERE id = ? LIMIT 1
`

func (q *Queries) GetSSHKeyByID(ctx context.Context, id int64) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, getSSHKeyByID, id)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrivateKey,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, name, description, private_key, public_key, last_used_at, created_at, updated_at FROM ssh_keys ORDER BY created_at DESC
`

func (q *Queries) ListSSHKeys(ctx context.Context) ([]SshKey, error) {
	rows, err := q.db.QueryContext(ctx, listSSHKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrivateKey,
			&i.PublicKey,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSSHKey = `-- name: UpdateSSHKey :one
UPDATE ssh_keys
SET
	name = ?,
	description = ?,
	private_key = ?,
	public_key = ?,
	last_used_at = ?
WHERE id = ?
RETURNING id, name, description, private_key, public_key, last_used_at, created_at, updated_at
`

type UpdateSSHKeyParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	PrivateKey  string  `json:"private_key"`
	PublicKey   string  `json:"public_key"`
	LastUsedAt  *int64  `json:"last_used_at"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateSSHKey(ctx context.Context, arg UpdateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, updateSSHKey,
		arg.Name,
		arg.Description,
		arg.PrivateKey,
		arg.PublicKey,
		arg.LastUsedAt,
		arg.ID,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrivateKey,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
